{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:09:33"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:09:33"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:09:33"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:10:58"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:10:58"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:10:58"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:11:04"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:11:04"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:11:04"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:11:46"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:11:46"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:11:46"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:12:47"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:12:47"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:12:47"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:12:58"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:12:58"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:12:58"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:13:03"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:13:03"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:13:03"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:13:26"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:13:26"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:13:26"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:13:31"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:13:31"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:13:31"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:13:50"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:13:50"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:13:50"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:15:23"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:15:23"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:15:23"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:15:24"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:15:24"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:15:24"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:15:50"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:15:50"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:15:50"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:16:17"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:16:17"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:16:17"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:22:33"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:22:33"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:22:33"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:23:07"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:23:07"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:23:07"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:23:28"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:23:28"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:23:28"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:23:48"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:23:48"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:23:48"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:24:08"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:24:08"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:24:08"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:24:17"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:24:17"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:24:17"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:24:26"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:24:26"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:24:26"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:24:55"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:24:55"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:24:55"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:25:04"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:25:04"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:25:04"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:25:23"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:25:23"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:25:23"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:25:33"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:25:33"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:25:33"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:25:38"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:25:38"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:25:38"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:25:45"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:25:45"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:25:45"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:28:08"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:28:08"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:28:08"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:28:26"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:28:26"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:28:26"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:28:33"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:28:33"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:28:33"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:29:32"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:29:32"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:29:32"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:30:01"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:30:01"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:30:01"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:30:44"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:30:44"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:30:44"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:32:39"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:32:39"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:32:39"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:37:00"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:37:00"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:37:00"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:38:20"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:38:20"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:38:20"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:38:32"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:38:32"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:38:32"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:38:37"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:38:37"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:38:37"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:38:44"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:38:44"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:38:44"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:39:10"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:39:10"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:39:10"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:40:05"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:40:05"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:40:05"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:40:55"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:40:55"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:40:55"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:41:07"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:41:07"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:41:07"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:42:10"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:42:10"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:42:10"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:44:35"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:44:35"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:44:35"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:44:50"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:44:50"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:44:50"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:45:04"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:45:04"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:45:04"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:45:35"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:45:35"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:45:35"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:46:19"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:46:20"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:46:20"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:48:23"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:48:23"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:48:23"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:48:34"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:48:34"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:48:34"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:49:30"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:49:30"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:49:30"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:49:32"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:49:32"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:49:32"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:49:47"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:49:56"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:49:57"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:49:57"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:50:13"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:50:13"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:50:13"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:50:23"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:50:23"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:50:23"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:50:27"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:50:27"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:50:27"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:50:45"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:50:45"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:51:04"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:51:04"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:51:04"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:51:50"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:51:50"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:51:50"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:51:52"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:51:52"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:51:52"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:52:22"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:52:51"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:52:51"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:52:51"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:52:52"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:52:52"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:52:52"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:53:09"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:53:21"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:53:29"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:53:41"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:53:49"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:54:01"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:54:09"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:54:11"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:54:11"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:54:11"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:54:21"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:54:21"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:54:21"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:56:11"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:56:11"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:56:11"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:57:55"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:57:55"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:57:55"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:58:13"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:58:33"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:58:53"}
{"message":"Successfully uploaded data to myBucket/myKey","level":"info","timestamp":"2019-02-17 19:59:13"}
{"message":"development, Picaso.io App listening on port 8080","level":"info","timestamp":"2019-02-17 19:59:22"}
{"message":"MONGODB connection errorMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","level":"error","timestamp":"2019-02-17 19:59:22"}
{"message":"MONGODB connection error","level":"error","timestamp":"2019-02-17 19:59:22"}
